name: firstworkflow
on: workflow_dispatch
jobs:
  deployosupdate:
    runs-on: ubuntu-latest
    steps:
    - name: install update
      run: sudo apt update
  deploynginx:
    runs-on: ubuntu-latest
    needs: deployosupdate
    steps:
    - name: install nginx
      run: |
        sudo apt install -y nginx
        sudo systemctl start nginx
        sudo systemctl enable nginx
    - name: verify nginx installation
      run: systemctl status nginx
      


      
    
  